const express = require('express');
const path = require('path');
const logger = require('morgan');
const cookieParser = require('cookie-parser');
const cors = require('cors');
require('dotenv').config();

const indexRouter = require('./routes/index');
const UserCtrl = require('./controllers/user');
const VideoCtrl = require('./controllers/video');
const PDFCtrl = require('./controllers/pdf');
const ImageCtrl = require('./controllers/image');
const PageCtrl = require('./controllers/page');
const EmailCtrl = require('./controllers/email');
const { catchError } = require('./controllers/error');

const app = express();

const variable = require('./constants/variable');

variable.country_codes();

app.use(cors());
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');
app.use(logger('dev'));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: false, limit: '50mb' }));
app.use(cookieParser());

// app.use(express.static('../crmgrow/dist'));

app.use(express.static(path.join(__dirname, 'public')));

app.get('/video', catchError(VideoCtrl.play));
app.get('/video/:id', catchError(VideoCtrl.playUserVideo)); // user video play
app.get('/video1/:id', catchError(VideoCtrl.play1)); // trackable video link
app.get('/video4', catchError(VideoCtrl.playExtensionVideo)); // video play sent via extension
app.get('/video5', catchError(VideoCtrl.playDirectSmsVideo)); // video play sent via mobile
app.get('/video6/:id', catchError(VideoCtrl.playUuidVideo)); // video play generated by trackable link
app.get('/pdf', catchError(PDFCtrl.play)); // normal pdf
app.get('/pdf/:id', catchError(PDFCtrl.playUserPdf)); // user pdf
app.get('/pdf1/:id', catchError(PDFCtrl.play1)); // trackable pdf link
app.get('/pdf4', catchError(PDFCtrl.playExtensionPdf)); // pdf sent via extension
app.get('/pdf5', catchError(PDFCtrl.playDirectSmsPdf)); // image sent via mobile
app.get('/pdf6/:id', catchError(PDFCtrl.playUuidPdf)); // pdf generated by trackable link
app.get('/image', catchError(ImageCtrl.play)); // normal image
app.get('/image1/:id', catchError(ImageCtrl.playUserImage)); // user image
app.get('/image/:id', catchError(ImageCtrl.play1)); // trackable image link
app.get('/image4', catchError(ImageCtrl.playExtensionImage)); // image sent via extension
app.get('/image5', catchError(ImageCtrl.playDirectSmsImage)); // image sent via mobile
app.get('/image6/:id', catchError(ImageCtrl.playUuidImage)); // image generated by trackable link
app.get('/demo', catchError(VideoCtrl.playDemo));
app.get('/embed/video/:video', catchError(VideoCtrl.embedPlay));
app.get('/unsubscribe', catchError(EmailCtrl.unSubscribePage));
app.get('/redirect', catchError(EmailCtrl.clickEmailLink));
app.get('/social-oauth/:social', catchError(UserCtrl.appSocial));
app.get('/social-oauth/:social/:source', catchError(UserCtrl.appSocial));
app.get(
  '/social-register/:social/:source',
  catchError(UserCtrl.appSocialRegister)
); // Social Sign up request
app.get(
  '/social-oauth-callback/:social/:source',
  catchError(UserCtrl.appSocialCallback)
);
app.get(
  '/social-register-callback/:social/:source',
  catchError(UserCtrl.appSocialRegisterCallback)
);
app.get(
  '/sync-social/:social/:action',
  catchError(UserCtrl.syncSocialRedirect)
);
app.get('/record', (req, res) => {
  res.render('record');
});

app.get('/auth', (req, res) => {
  res.render('auth');
});

app.use('/api', indexRouter);

// app.get('*', catchError(PageCtrl.display), (req, res) => {
//  res.sendFile(path.join(__dirname, '../crmgrow/dist', 'index.html'));
// });

module.exports = app;
