const system_settings = {
  SUBSCRIPTION_FREE_TRIAL: 14,
  DEFAULT_PACKAGE: 'PRO',
  MINIMAL_PACKAGE: 'MINIMAL',
  EXT_FREE_PACKAGE: 'EXT_FREE',
  EXT_PACKAGE: 'EXT',
  EMAIL_ONE_TIME: 15,
  EMAIL_DAILY_LIMIT: {
    BASIC: 500,
    GMAIL: 500,
    GSUIT: 1500,
    OUTLOOK: 300,
    MICROSOFT: 2000,
  },
  MATERIAL_TRACK_LIMIT: {
    EXT_FREE: 1,
  },
  TEXT_ONE_TIME: 15,
  TEXT_MONTHLY_LIMIT: {
    PRO: 250,
    EVO_PRO: 250,
    ELITE: 1000,
    EVO_ELITE: 1000,
  },
  EXT_EMAIL_LIMIT: {
    EXT_FREE: 1,
  },
  ASSISTANT_LIMIT: {
    PRO: 1,
    EVO_PRO: 1,
    ELITE: 2,
    EVO_ELITE: 2,
  },
  CALENDAR_LIMIT: {
    PRO: 1,
    EVO_PRO: 1,
    ELITE: 4,
    EVO_ELITE: 4,
  },
  SCHEDULER_LIMIT: {
    LITE: 1,
    PRO: 3,
    EVO_PRO: 3,
  },
  LANDING_PAGE_LIMIT: {
    PRO: 1,
    EVO_PRO: 1,
    ELITE: 3,
    EVO_ELITE: 3,
  },
  CONTACT_UPLOAD_LIMIT: {
    LITE: 200,
    PRO: 2000,
    ELITE: 10000,
    EVO_PRO: 5000,
    EVO_ELITE: 500000,
  },
  TEAM_OWN_LIMIT: {
    PRO: 1,
    ELITE: 2,
    EVO_PRO: 1,
    EVO_ELITE: 2,
  },
  MATERIAL_UPLOAD_LIMIT: {
    LITE: 10,
    EVO_PRO: 100,
    PRO: 100,
    EXT_PAID: 100,
    EXT_FREE: 10,
  },
  SUB_ACCOUNT_LIMIT: {
    ELITE: 0,
    EVO_ELITE: 3,
  },
  VIDEO_RECORD_LIMIT: {
    LITE: 600000,
    EXT_FREE: 600000,
    PRO: 7200000,
    EXT_PAID: 7200000,
    EVO_PRO: 7200000,
    ELITE: 60000000,
    EVO_ELITE: 60000000,
  },
  PASSWORD: {
    USER: process.env.DEFAULT_PASS,
    ADMIN: process.env.ADMIN_DEFAULT_PASS,
    SUPPORT: process.env.SUPPORT_DEFAULT_PASS,
  },
  COMPANY: {
    DEFAULT: 'eXp Realty',
  },
  ADMIN_ACCOUNT: 'support@crmgrow.com',
  ONBOARD_ACCOUNT: 'hello@crmgrow.com',
  LEAD: '5f16d58d0af09220208b6e11',
  AUTO_FOLLOW_UP: 'has reviewed material',
  AUTO_FOLLOW_UP2: 'didn`t watch mater``ial',
  AUTOMATION_ASSIGN_LIMIT: {
    PRO: 300,
    EVO_PRO: 300,
    ELITE: 2000,
    EVO_ELITE: 2000,
  },
  PIPE_LIMIT: {
    LITE: 1,
    PRO: 2,
    EVO_PRO: 2,
    ELITE: 5,
    EVO_ELITE: 5,
  },
  THUMBNAIL: {
    WIDTH: 400,
    HEIGHT: 220,
  },
  IMAP_PORT: 587,
  ONBOARD_PRICING_30_MINS: 5000,
  ONBOARD_PRICING_1_HOUR: 4900,
  TWILIO_EXCHANGE_NUMBER: 1000,
  SCHEDULE_LINK_30_MINS: 'https://calendly.com/coachwithdaniel/crm-grow-30',
  SCHEDULE_LINK_1_HOUR:
    'https://calendly.com/support-1196/crmgrow-1-hour-session',
  CAMPAIGN_MAIL_START: {
    SMTP: 500,
    GMAIL: 150,
    GSUIT: 500,
    OUTLOOK: 150,
    MICROSOFT: 500,
    AWS: 5000,
  },
  LABEL_LIMIT: 50,
  CAMPAIGN_MAIL_LIMIT: {
    GMAIL: 400,
    GSUIT: 1500,
    OUTLOOK: 250,
    MICROSOFT: 1000,
    AWS: 5000,
  },
  DEMO_VIDEO: '60ad6077af664b0016ebb176',
  WEBINAR_LINK: 'https://calendly.com/support-1196/crmgrow-live-demo',
  TIME_ZONE: 'America/New York',
  DEFAULT_STAGES: [
    'Lead',
    '30% Committed',
    '60% Committed',
    '90% Committed',
    'Application',
    'Submitted',
  ],
  SMS_CREDIT: [
    {
      PRICE: 600,
      AMOUNT: 250,
    },
    {
      PRICE: 1000,
      AMOUNT: 500,
    },
    {
      PRICE: 1500,
      AMOUNT: 1000,
    },
  ],
  AUTOMATION_BRANCH_LIMIT: 2,
  DIALER_FREE_TRIAL: 14,
  REFERRAL_DEEP: 3,
  USER_VERSION: 1,
  REPLACE_NAME: 'crmgrow',
  PACKAGE_LEVEL: [0, 29, 49, 99],
  MLM_LEVEL: [0, 0.1, 0.15, 0.12],
  PRO_CODE: {
    EVO: 'QWERAS',
  },
  OFFER: {
    ONE_MONTH_TRIAL: '1 free subscription months',
    TWENTY_PERCENT_DISCOUNT: '20% discount coupon',
  },
};

module.exports = system_settings;
